services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - /home/ziko/data/web:/var/www/html
    networks:
      inception:
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    volumes:
      - /home/ziko/data/web:/var/www/html
    networks:
      inception:

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
      # - /home/ziko/data/db:/var/www/html
    networks:
      inception:

networks:
  inception: