services:
  nginx:
    restart: always
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_files:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    restart: always
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    restart: always
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/web'

  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/db'