background=NO

listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_root=/var/www/html

chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=127.0.0.1

secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
