# --- Basic Server Settings ---
listen=NO
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

ftpd_banner=Welcome to My FTP server built by zouazrou!

# --- Security & Jail (Chroot) ---
# This prevents users from leaving their assigned directory
chroot_local_user=YES
allow_writeable_chroot=YES

# --- Passive Mode Settings ---
# CRITICAL: These must match your docker-compose.yml ports
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
# Note: In a production server, you would set 'pasv_address=YOUR_PUBLIC_IP'